export default [
{
  number: 69,
  title: 'Be More Verbose',
  description: 'Chase and Jonathan discuss a blog by Jon Pitcherella about writing better Ember tests, the new 1.0 release of one way controls, and much more.',
  slug: 'be-more-verbose',
  releaseDate: 'August 09, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-69-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '15:03',
  length: 145633327
},
{
  number: 68,
  title: 'Alpha Something',
  description: 'Chase and Jonathan discuss the newly released Ember 2.9 alpha, lazy engines, and a new podcast called CareerJS from some Ember friends.',
  slug: 'alpha-something',
  releaseDate: 'August 01, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-68-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '23:43',
  length: 28460896
},
{
  number: 67,
  title: 'Nondeterministic Finite Podcast',
  description: 'Chase returns from vacation rejoining Jonathan to discuss the asset service RFC, Nathan Hammond\'s treatise on route recognition, and Jonathan\s new addon.',
  slug: 'nondeterministic-finite-podcast',
  releaseDate: 'July 25, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-67-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '23:43',
  length: 28460896
},
{
  number: 66,
  title: 'Bug Integrat',
  description: 'Jon is joined by Frontside founder Charles Lowell to discuss everything from EmberMap to Percy in this fun episode.',
  slug: 'bug-integrat',
  releaseDate: 'July 18, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-66-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '25:20',
  length: 30408014,
  guests: [
    {
      name: 'Charles Lowell',
      guestInfoURL: 'https://twitter.com/cowboyd',
      avatarURL: 'assets/images/charles-lowell.jpg',
      tagLine: 'Gentleman Developer',
      bio: 'Charles has been delivering bullet-proof software for over 18 years. An avid contributor to open source, he founded the Frontside in 2005 to help businesses deliver game-changing user interfaces to their customers. Also, he really, really, really, really likes to code. Really.'
    },
  ]
},
{
  number: 65,
  title: 'Go catch\'em all',
  description: 'Chase and Jon discuss Ember Exam, the new Fastboot driven Acorns site, and a DI blog post by Lauren Tan.',
  slug: 'go-catchem-all',
  releaseDate: 'July 11, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-65-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '19:54',
  length: 23885056
},
{
  number: 64,
  title: 'Instant Win',
  description: 'Chase and Jon once again unite with Robert Jackson and Dan McClain of Ember Land to form EmberWeekendLand. With their powers combined, they recap Wicked Good Ember and somehow fill 45 minutes with random tangents.',
  slug: 'instant-win',
  releaseDate: 'July 4, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-64-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '44:01',
  length: 52814806,
  guests: [
    {
      name: 'Robert Jackson',
      guestInfoURL: 'https://twitter.com/rwjblue',
      avatarURL: 'assets/images/robert-jackson.jpg',
      tagLine: 'Ember core team  member and Frontend Developer at Aptible',
      bio: 'Robert is an Ember.js core team member, and general open source addict. Outside of Aptible, Robert enjoys spending time with his wife and two rambunctious boys. He is @rwjblue on the web.'
    },
    {
      name: 'Dan McClain',
      guestInfoURL: 'https://twitter.com/_danmcclain',
      avatarURL: 'assets/images/dan-mcclain.jpg',
      tagLine: 'Dan is a partner and lead developer at DockYard.',
      bio: 'He has been working on web applications for the past 7 years, starting with .Net, then later working with Rails. As of recent, DockYard has bet the company on Ember and Elixir, where Dan develops rich client applications for their clients.'
    }
  ]
},
{
  number: 63,
  title: 'Today I Learnt',
  description: 'Chase and Jonathan discuss Jon\'s exploration into Progressive Web Applications, Ember Time Machine,  and a great blog post about ember addons by Brian Sipple.',
  slug: 'today-i-learnt',
  releaseDate: 'June 20, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-63-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '13:54',
  length: 16675456
},
{
  number: 62,
  title: 'Game Changeset Match',
  description: 'Chase and Jonathan discuss the business side of mobile web, Ember actions vs events, and Ember Changeset + Validations.',
  slug: 'game-changeset-match',
  releaseDate: 'June 13, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-62-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '18:16',
  length: 21928145
},
{
  number: 61,
  title: 'League of Emburritos',
  description: 'Chase and Jonathan discuss GEMConf, css linting, a new Ember Vim plugin, and Riot\'s Ember usage.',
  slug: 'league-of-emburritos',
  releaseDate: 'June 06, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-61-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '13:02',
  length: 15635296
},
{
  number: 60,
  title: 'Module Impossible',
  description: 'Chase and Jonathan review their notes on the new module unification RFC and a talk by Robert Jackson at Ember NYC about why it is necessary.',
  slug: 'module-impossible',
  releaseDate: 'May 30, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-60-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '20:53',
  length: 25063883
},
{
  number: 59,
  title: 'GemConf Time',
  description: 'Chase and Jonathan discuss the various speakers for the upcoming Global Ember Meetup conference, their training, and call ahead to a future episode on module reunification.',
  slug: 'gem-conf-time',
  releaseDate: 'May 16, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-59-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '11:16',
  length: 13533856
},
{
  number: 58,
  title: 'Get with the Times',
  description: 'Chase and Jonathan discuss inaugural issue of the Ember.js Times, a wonderful series on the PEEP stack by Mike North, and how to build Pacman in Ember js by Jeffrey Biles.',
  slug: 'get-with-the-times',
  releaseDate: 'May 09, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-58-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '10:12',
  length: 12250300
},
{
  number: 57,
  title: 'Google Can See Us Now',
  description: 'Chase and Jonathan discuss the evolution of the Ember Weekend Ember application.  The shift to an elixir backend, hosting on Heroku, and Fastboot',
  slug: 'google-can-see-us-now',
  releaseDate: 'May 02, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-57-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '22:06',
  length: 26523616
},
{
  number: 56,
  title: 'didInsertEpisodeTitle',
  description: 'Chase and Jonathan talk about Composable helpers, route action handlers, JSON API, and web vs. mobile development.',
  slug: 'did-insert-episode-title',
  releaseDate: 'April 25, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-56-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '17:00',
  length: 20403116
},
{
  number: 55,
  title: 'Just a Little Reacty',
  description: 'Chase and Jonathan discuss their upcoming Ember training, whether or not controllers are \'dead\', and ember redux.',
  slug: 'just-a-litte-reacty',
  releaseDate: 'April 18, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-55-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '14:42',
  length: 17648416
},
{
  number: 54,
  title: 'Like Stealing Candy From a Baby',
  description: 'Chase and Jonathan are joined by Dockyarder and Addon author extrodinaire Lauren Tan discussing everything from Addon authorship to the joy and pain of consulting work.  Be sure to tune in for this exiting episode!',
  slug: 'like-stealing-candy-from-a-baby',
  releaseDate: 'April 11, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-54-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '01:00:50',
  length: 73005376,
  guests: [
    {
      name: 'Lauren Tan',
      guestInfoURL: 'https://twitter.com/sugarpirate_',
      avatarURL: 'assets/images/lauren-tan.jpg',
      tagLine: 'Applications Manager',
      bio: 'Lauren is co-founder at ThePriceGeek, and Senior Developer at DockYard, a user experience driven software consultancy based in Boston, MA. She is also an active contributor to the Ember.js community, and a regular speaker at leading JavaScript events and conferences.'
    }
  ]
},
{
  number: 53,
  title: 'Killer Queen For Days',
  description: 'Chase and Jonathan discuss goings on in Ember land post EmberConf.',
  slug: 'killer-queen-for-days',
  releaseDate: 'April 05, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-53-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '14:41',
  length: 17614806
},
{
  number: 52,
  title: 'See you at EmberConf',
  description: 'Chase and Jonathan discuss the new testdouble.js library, A vim workshop, gush over Emberconf events, and then have a long winded discussion about the Ember Weekend Site.',
  slug: 'see-you-at-emberconf',
  releaseDate: 'March 28, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-52-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '36:53',
  length: 44269108
},
{
  number: 51,
  title: 'You can have Glimmer two',
  description: 'Chase and Jonathan discuss EmberCLI Mirage, the Glimmer 2 testing porting issue, and much more.',
  slug: 'you-can-have-glimmer-two',
  releaseDate: 'March 21, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-51-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '17:01',
  length: 20430284
},
{
  number: 50,
  title: 'Await for it',
  description: 'Chase and Jonathan talk about the Ember survey, Ember map, the module RFC, and the Grand Testing Unification.',
  slug: 'await-for-it',
  releaseDate: 'March 14, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-50-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '25:01',
  length: 30023492
},
{
  number: 49,
  title: 'I found your subtweets',
  description: 'Chase and Jonathan are joined by frontsider and Ember Data core team member Stanley Stuart discussing everything from Fastboot to the future of Ember Data.  Be sure to tune in for this exiting episode!',
  slug: 'i-found-your-subtweets',
  releaseDate: 'March 7, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-49-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '01:04:20',
  length: 77195409,
  guests: [
    {
      name: 'Stanley Stuart',
      guestInfoURL: 'https://twitter.com/fivetanley',
      avatarURL: 'assets/images/stanley-stuart.jpg',
      tagLine: 'Prancersizer',
      bio: 'Stanley Stuart originally hails from Salt Lake City. He is known for his open-source contributions and as a member of the Ember.js Release team, but is perhaps best known as the first Prancercising JavaScript developer. Stanley loves hanging out on Austin\'s many patio spots and crafting hilarious tweets.'
    }
  ]
},
{
  number: 48,
  title: 'Whack-a-hamster',
  description: 'Chase and Jonathan can\'t stop talking about ember-concurrency, Ember LTS, Dockyard addons, and The Hanselminutes Podcast.',
  slug: 'whack-a-hamster',
  releaseDate: 'February 29, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-48-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '22:36',
  length: 27121810
},
{
  number: 47,
  title: 'Hardcore Parkour',
  description: 'Chase and Jonathan discuss Ember concurrency, Ember data default values, and much more!',
  slug: 'hardcore-parkour',
  releaseDate: 'February 22, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-47-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '15:20',
  length: 18397957
},
{
  number: 46,
  title: 'Team Tofu Burrito',
  description: 'Chase and Jonathan debate episode titles, Ember Data updates, metaphors, Ancient City Ruby, Angular, magic and Real World Ember.',
  slug: 'team-tofu-burrito',
  releaseDate: 'February 15, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-46-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '14:23',
  length: 17267377
},
{
  number: 45,
  title: 'Global Ember Weekend',
  description: 'Chase and Jonathan discuss the Ember Hearth project, EmberCLI redux, fastboot (again), and much more!',
  slug: 'global-ember-weekend',
  releaseDate: 'February 08, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-45-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '16:57',
  length: 20352961
},
{
  number: 44,
  title: 'Fastboot Has a Logo Now',
  description: 'Chase and Jonathan discuss the problem with using attrs, fastboot, a few Ember NYC talks, and much more!',
  slug: 'fastboot-has-a-logo-now',
  releaseDate: 'February 01, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-44-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '17:42',
  length: 21236945
},
{
  number: 43,
  title: 'Application Instance Instances',
  description: 'Chase and Jonathan discuss the new getOwner API, Functional Templates focussing on a blog post by Charles Lowell, the possible ArrayProxy deprecation and more!',
  slug: 'application-instance-instances',
  releaseDate: 'January 25, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-43-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '21:06',
  length: 25325630
},
{
  number: 42,
  title: 'Start Your Engines',
  description: 'Chase and Jonathan discuss the new ember-engines addon, ember processes, continuous upgrades, security, unit tests, and ember-cli-mirage',
  slug: 'start-your-engines',
  releaseDate: 'January 18, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-42-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '22:15',
  length: 26707508
},
{
  number: 41,
  title: 'And We\'re Back',
  description: 'Chase and Jonathan discuss how Ember is not Rails, Ember Data has been addonized, Emberland is back, and Ember is no longer an MVC framework. Welcome to 2016!',
  slug: 'and-were-back',
  releaseDate: 'January 11, 2016',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-41-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '18:17',
  length: 21937549
},
{
  number: 40,
  title: 'Happy New Years',
  description: 'In the final episode of 2015, Chase and Jonathan talk about the future of JavaScript jobs, 100 episodes of Ember Screencasts, and do a year-end review of Ember Weekend.',
  slug: 'happy-new-years',
  releaseDate: 'December 28, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-40-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '18:15',
  length: 21908814
},
{
  number: 39,
  title: 'Whacked Out Hegemony - Part 2',
  description: 'Chase and Jonathan are joined by Chris Thoburn.  Chris talks about recycling DOM, Pokedex, webworkers, Backburner, and Skyrocket.',
  slug: 'whacked-out-hegemony-part-2',
  releaseDate: 'December 21, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-39-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '58:37',
  length: 70337744,
  guests: [
    {
      name: 'Chris Thoburn',
      guestInfoURL: 'https://twitter.com/runspired',
      avatarURL: 'assets/images/chris-thoburn.jpg',
      tagLine: 'Author of Smoke and Mirrors, Ember Consultant',
      bio: 'Outdoor enthusiast. Future ultra-marathon addict. Tech guy. Passionate about personal growth and leaving things better than found.'
    }
  ]
},
{
  number: 38,
  title: 'Whacked Out Hegemony - Part 1',
  description: 'Chase and Jonathan are joined by Chris Thoburn.  Chris talks about the future of Ember, webworkers, his project Smoke and Mirrors and much more.',
  slug: 'whacked-out-hegemony-part-1',
  releaseDate: 'December 15, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-38-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '48:28',
  length: 58175655,
  guests: [
    {
      name: 'Chris Thoburn',
      guestInfoURL: 'https://twitter.com/runspired',
      avatarURL: 'assets/images/chris-thoburn.jpg',
      tagLine: 'Author of Smoke and Mirrors, Ember Consultant',
      bio: 'Outdoor enthusiast. Future ultra-marathon addict. Tech guy. Passionate about personal growth and leaving things better than found.'
    }
  ]
},
{
  number: 37,
  title: 'Update your package.json',
  description: 'Chase and Jonathan are joined by Katie Gengler.  Katie talks to use about her experience as a developer, addon author, and Ember Observer creator.',
  slug: 'update-your-package-json',
  releaseDate: 'December 7, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-37-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '42:21',
  length: 50825320,
  guests: [
    {
      name: 'Katie Gengler',
      guestInfoURL: 'https://twitter.com/katiegengler',
      avatarURL: 'assets/images/katie-gengler.jpg',
      tagLine: 'Developer / Co-Founder at Code All Day',
      bio: 'Katie has in-depth experience building rich, interactive web apps with modern UX. She also brings expertise in managing product development and building development teams.'
    }
  ]
},
{
  number: 36,
  title: 'Easy PRs',
  description: 'Chase and Jonathan discuss ember-views deep dive, Ember Global Meetup\'s Testing Day, functional programming in Ember, and the Ember 2.3 Beta release',
  slug: 'easy-prs',
  releaseDate: 'November 23, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-36-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '25:51',
  length: 31030251
},
{
  number: 35,
  title: 'Copy Pasta Problems',
  description: 'Chase and Jonathan talk about the Ember Inspector, Ember Data as an addon, Ember Conf CFP, application architecture, and Ember views',
  slug: 'copy-pasta-problems',
  releaseDate: 'November 16, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-35-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '10:17',
  length: 12338071
},
{
  number: 34,
  title: 'Adventures in the Amazon',
  description: 'Chase and Jonathan talk about the move to S3 static hosting, Ember 101, Ember Data caching, kebab actions, and the upcoming resource episode',
  slug: 'adventures-in-the-amazon',
  releaseDate: 'November 9, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-34-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '21:45',
  length: 26107737
},
{
  number: 33,
  title: 'Context Clues',
  description: 'Chase and Jonathan go over Jon\'s FastBoot PRs, contextual components, ember-cli-rails-routes, and Dan McClain\'s closure action tips',
  slug: 'context-clues',
  releaseDate: 'November 2, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-33-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '20:13',
  length: 24272896
},
{
  number: 32,
  title: 'I <3 EmberNYC',
  description: 'Chase and Jonathan talk about their freshly launched blog, a wonderful blog post by Jeffrey Biles, and go into depth about a recent talk by Edward Faulkner at EmberNYC',
  slug: 'i-<3-ember-nyc',
  releaseDate: 'October 26, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-32-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '16:28',
  length: 19755279
},
{
  number: 31,
  title: 'Hijacking TIL for fun and profit',
  description: 'Chase and Jonathan talk about using TIL posts as a backend for the Ember Weekend blog and quickly cover a recent talk by Tom Dale about progessive enhancement',
  slug: 'hijacking-til',
  releaseDate: 'October 19, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-31-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '13:22',
  length: 16038577
},
{
  number: 30,
  title: 'Ember Weekend LTS',
  description: 'Chase and Jonathan discuss the most recent Global Ember Meetup, Routable Modals, Fastboot, and Ember LTS versions',
  slug: 'ember-weekend-lts',
  releaseDate: 'October 12, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-30-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '15:48',
  length: 18965337
},
{
  number: 29,
  title: 'The Rule of Least Power',
  description: 'Chase and Jonathan discuss the routing RFC, slow JS on Android, HTMLBars\'s lack of power (good thing), and the benefits of page objects.',
  slug: 'the-rule-of-least-power',
  releaseDate: 'October 5, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-29-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '15:37',
  length: 18749565
},
{
  number: 28,
  title: 'Const all day, fat arrow for life!',
  description: 'Chase and Jonathan talk about the past Global Ember Meetup, ember-data and our experience on LiveCoding.tv, and much more.',
  slug: 'const-all-day',
  releaseDate: 'September 21, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-28-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '17:34',
  length: 21082822
},
{
  number: 27,
  title: 'Stickolas Cage',
  description: 'Chase and Jonathan make some corections, discuss ember-cli-cordova and a blog post about testing the Ember/Rails boundary.',
  slug: 'stickolas-cage',
  releaseDate: 'September 21, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-27-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '17:35',
  length: 21109990
},
{
  number: 26,
  title: 'Real For Me',
  description: 'Chase and Jonathan talk about their experiences attending Ember Global Meetup with @embersherpa, strong-attrs, and Glimmer components.  You won\'t want to miss this!',
  slug: 'real-for-me',
  releaseDate: 'September 14, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-26-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '17:09',
  length: 20579704
},
{
  number: 25,
  title: 'Lingua Franca',
  description: 'Chase and Jonathan discuss creating a custom adapter/serializer for tranient data, The Frontside Podcast, improved Ember guide organization, and select views in Ember 2.0.',
  slug: 'lingua-franca',
  releaseDate: 'September 7, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-25-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '12:47',
  length: 15345288
},
{
  number: 24,
  title: 'tips-and-tricks',
  description: 'Chase and Jonathan review some developer tips and tricks (with some help from @rwjblue).',
  slug: 'tips-and-tricks',
  releaseDate: 'August 31, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-24-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '17:41',
  length: 21225451
},
{
  number: 23,
  title: 'Testing Talk',
  description: 'Chase and Jonathan discuss the new ember-cli-qunit stubbing feature, and then talk testing.',
  slug: 'testing-talk',
  releaseDate: 'August 24, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-23-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '25:52',
  length: 31045402
},
{
  number: 22,
  title: 'Clear the runway',
  description: 'Chase and Jonathan discuss Pretender changes, the excellent addon ember-cli-deprecation-workflow, new Ember.js guides, and of course Ember 2.0!',
  slug: 'clear-the-runway',
  releaseDate: 'August 17, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-22-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '15:51',
  length: 19025418
},
{
  number: 21,
  title: 'Componentize all the things!',
  description: 'Chase and Jonathan speak with Mike North about Community, Material design, development at Yahoo, and a LOT more!',
  slug: 'componentize-all-the-things',
  releaseDate: 'August 10, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-21-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '31:38',
  length: 37965238,
  guests: [
    {
      name: 'Mike North',
      guestInfoURL: 'https://twitter.com/michaellnorth',
      avatarURL: 'assets/images/mike-north.jpg',
      tagLine: 'Principal Software Engineer at Yahoo',
      bio: 'UI lead for Yahoo Ad Manager Plus, our Demand Side Platform and flagship ad product. A driving force in the adoption of modern web frameworks across Yahoo'
    }
  ]
},
{
  number: 20,
  title: 'Faking the funk',
  description: 'Chase and Jonathan discuss testing an EmberJax project (with advanced techniques like page objects and mirage), component integration tests, ember twiddle, and core notes.',
  slug: 'faking-the-funk',
  releaseDate: 'August 03, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-20-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '23:40',
  length: 28405467
},
{
  number: 19,
  title: 'Consumer Driven Weekend',
  description: 'Chase and Jonathan speak with Sam Selikoff about the Ember Community, Consumer Driven Contracts, and his project Ember CLI Mirage.',
  slug: 'consumer-driven-weekend',
  releaseDate: 'July 27, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-19-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '1:00:00',
  length: 72005401,
  guests: [
    {
      name: 'Sam Selikoff',
      guestInfoURL: 'https://twitter.com/samselikoff',
      avatarURL: 'assets/images/sam-selikoff.jpg',
      tagLine: 'Frontend Developer at TED',
      bio: "I'm a front-end web developer at TED interested in JavaScript, data visualization and economics"
    }
  ]
},
{
  number: 18,
  title: 'Reliving All My CS Days',
  description: 'Chase and Jonathan discuss suave code, workshops, metrics, and the ASTs behind Handlebars and HTMLBars',
  slug: 'reliving-all-my-cs-days',
  releaseDate: 'July 20, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-18-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '14:27',
  length: 17335296
},
{
  number: 17,
  title: 'Ember Training Recap',
  description: 'Chase and Jonathan discuss the what they learned at Ember 2.0 Training in Chicago.',
  slug: 'ember-training-recap',
  releaseDate: 'July 13, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-17-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '23:00',
  length: 27597761
},
{
  number: 16,
  title: 'Resources and Junk',
  description: 'Chase and Jonathan talk about ten resources that will help you get up and running with Ember.js',
  slug: 'resources-and-junk',
  releaseDate: 'July 6, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-16-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '19:08',
  length: 22965206
},
{
  number: 15,
  title: 'EmberJax Edits a Podcast',
  description: 'Chase and Jonathan talk about EmberJax, Ember.Evented, and Handlebars printing.',
  slug: 'emberjax-edits-a-podcast',
  releaseDate: 'June 29, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-15-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '16:40',
  length: 20005532
},
{
  number: 14,
  title: 'Ember IsLand 2.0 Beta',
  description: 'Chase and Jonathan team up with Dan and Robert (from Ember.Land) for a crossover episode in which they discuss all things Wicked Good Ember 2015',
  slug: 'ember-island-two-oh-beta',
  releaseDate: 'June 21, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-14-ember-weekend',
  author: 'Chase McCarthy, Jonathan Jackson, Dan McClain, and Robert Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '22:46',
  length: 27325565,
  guests: [
    {
      name: 'Robert Jackson',
      guestInfoURL: 'https://twitter.com/rwjblue',
      avatarURL: 'assets/images/robert-jackson.jpg',
      tagLine: 'Ember core team  member and Frontend Developer at Aptible',
      bio: 'Robert is an Ember.js core team member, and general open source addict. Outside of Aptible, Robert enjoys spending time with his wife and two rambunctious boys. He is @rwjblue on the web.'
    },
    {
      name: 'Dan McClain',
      guestInfoURL: 'https://twitter.com/_danmcclain',
      avatarURL: 'assets/images/dan-mcclain.jpg',
      tagLine: 'Dan is a partner and lead developer at DockYard.',
      bio: 'He has been working on web applications for the past 7 years, starting with .Net, then later working with Rails. As of recent, DockYard has bet the company on Ember and Elixir, where Dan develops rich client applications for their clients.'
    }
  ]
},
{
  number: 13,
  title: 'The Most Interesting Episode',
  description: 'Chase and Jonathan talk about Ember 1.13 and Ember 2.0.0-beta along with the upcoming talks at Wicked Good Ember.',
  slug: 'the-most-interesting-episode',
  releaseDate: 'June 14, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-13-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '14:53',
  length: 17860357
},
{
  number: 12,
  title: 'The Curiously Strong Weekend',
  description: 'Chase and Jonathan talk about Ember Simple Auth + Mirage, QUnit helpers, an RFC by Tom Dale, Breadcrumbs and blog posts, component actions, and the growing Ember community.',
  slug: 'the-curiously-strong-weekend',
  releaseDate: 'June 8, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-12-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '19:25',
  length: 23301663
},
{
  number: 11,
  title: 'E3r W5d with R4t D4a',
  description: 'Chase and Jonathan are joined by Robert Deluca and talk about accessiblity, i18n, jsconf, and a whole lot more!',
  slug: 'e3r-w5d-with-r4t-d4a',
  releaseDate: 'June 1, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-11-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '17:38',
  length: 21157532,
  guests: [
    {
      name: 'Robert Deluca',
      guestInfoURL: 'https://twitter.com/robdel12',
      avatarURL: 'assets/images/robert-deluca.jpg',
      tagLine: 'JavaScript Developer at The Frontside',
      bio: 'Robert is a JavaScript developer at The Frontside in Austin, Texas. He’s a full-time Ember developer and has a personal dedication to accessibility on the web.'
    }
  ]
},
{
  number: 10,
  title: 'Meh, Ship it',
  description: 'Chase and Jonathan talk about the growing ember-weekend community, there adventures in fastboot, and a new RFC by Yehuda Katz.',
  slug: 'meh-ship-it',
  releaseDate: 'May 26, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-10-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '13:15',
  length: 15911622
},
{
  number: 9,
  title: 'Interview with the Emberokai',
  description: 'Chase and Jonathan are joined by Paul Elliott, a lead developer at Heroku working on the Dashboard.',
  slug: 'interview-with-the-emberokai',
  releaseDate: 'May 18, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-9-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '18:58',
  length: 36405835,
  guests: [
    {
      name: 'Paul Elliott',
      guestInfoURL: 'https://twitter.com/p_elliott',
      avatarURL: 'assets/images/paul-elliott.jpg',
      tagLine: 'Lead Engineer on the Human Interface Team (HIT) at Heroku',
      bio: 'Paul is one of the engineers working on the Heroku Dashboard, which is an ember-cli app running on the Heroku platform. The team is distributed and does almost exclusively ember development, focusing on application architecture and new features.'
    }
  ]
},
{
  number: 8,
  title: 'The Most Private of All APIs',
  description: 'Chase and Jonathan celebrate Glimmer and discuss exploring FastBoot, stubbing services, and the SV Ember meetup.',
  slug: 'the-most-private-of-all-apis',
  releaseDate: 'May 11, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-8-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '13:47',
  length: 26455898,
},
{
  number: 7,
  title: 'Champions needed',
  description: 'Chase and Jonathan discuss routable components, ember-cli-mirage (again), JSON API, and the new EmberJax twitter account.',
  slug: 'champions-needed',
  releaseDate: 'May 4, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-7-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '17:23',
  length: 33384826
},
{
  number: 6,
  title: 'Ember in Atlanta',
  description: 'Chase and Jonathan recap their RailsConf experience and talk about Ember meetups',
  slug: 'ember-in-atlanta',
  releaseDate: 'April 27, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-6-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '14:26',
  length: 27729838
},
{
  number: 5,
  title: 'Wicked Good Design',
  description: 'Chase and Jonathan discuss the site redesign, Wicked Good Ember, Ember in Viewport, security patches, the run loop, and Ember Islands.',
  slug: 'wicked-good-design',
  releaseDate: 'April 20, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-5-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '13:40',
  length: 26258621
},
{
  number: 4,
  title: 'IE: Seeya L8er',
  description: "Chase and Jonathan talk Polymer, Ember 2.0 training, Netflix's freedom of responsiblity, and spend some extra time talking about IE8 support.",
  slug: 'ie-seeya-l8er',
  releaseDate: 'April 13, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-4-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '13:46',
  length: 26445867
},
{
  number: 3,
  title: 'Broccoli, but not the vegetable',
  description: 'Chase and Jonathan talk turbolinks, broccoli, and ember-watson.  Spending a little more time than usual discussing the new broccoli tree api.',
  slug: 'broccoli-but-not-the-vegetable',
  releaseDate: 'April 6, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-3-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '14:06',
  length: 20298732
},
{
  number: 2,
  title: 'The Weekend Strikes Back',
  description: "Chase and Jon discuss Ember's new versioned guides, testing in Ember CLI, and an Ember dependency guide for Rubyists.",
  slug: 'the-weekend-strikes-back',
  releaseDate: 'March 30, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-2-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '12:35',
  length: 18194725
},
{
  number: 1,
  title: 'Our First Foray',
  description: "Chase and Jon kick off Ember Weekend discussing EmberSherpa's workshop, EmberObserver, and some resources for beginners.",
  slug: 'our-first-foray',
  releaseDate: 'March 24, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-1-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/YyAd2Ee.png',
  duration: '10:16',
  length: 14806121
}
];

