export default [
{
  number: 25,
  title: 'Lingua Franca',
  description: 'Chase and Jonathan discuss creating a custom adapter/serializer for tranient data, The Frontside Podcast, improved Ember guide organization, and select views in Ember 2.0.',
  slug: 'lingua-franca',
  releaseDate: 'September 7, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-25-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '12:47'
},
{
  number: 24,
  title: 'tips-and-tricks',
  description: 'Chase and Jonathan review some developer tips and tricks (with some help from @rwjblue).',
  slug: 'tips-and-tricks',
  releaseDate: 'August 31, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-24-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '17:41'
},
{
  number: 23,
  title: 'Testing Talk',
  description: 'Chase and Jonathan discuss the new ember-cli-qunit stubbing feature, and then talk testing.',
  slug: 'testing-talk',
  releaseDate: 'August 24, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-23-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '25:52'
},
{
  number: 22,
  title: 'Clear the runway',
  description: 'Chase and Jonathan discuss Pretender changes, the excellent addon ember-cli-deprecation-workflow, new Ember.js guides, and of course Ember 2.0!',
  slug: 'clear-the-runway',
  releaseDate: 'August 17, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-22-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '15:51'
},
{
  number: 21,
  title: 'Componentize all the things!',
  description: 'Chase and Jonathan speak with Mike North about Community, Material design, development at Yahoo, and a LOT more!',
  slug: 'componentize-all-the-things',
  releaseDate: 'August 10, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-21-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '31:38'
},
{
  number: 20,
  title: 'Faking the funk',
  description: 'Chase and Jonathan discuss testing an EmberJax project (with advanced techniques like page objects and mirage), component integration tests, ember twiddle, and core notes.',
  slug: 'faking-the-funk',
  releaseDate: 'August 03, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-20-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '23:40'
},
{
  number: 19,
  title: 'Consumer Driven Weekend',
  description: 'Chase and Jonathan speak with Sam Selikoff about the Ember Community, Consumer Driven Contracts, and his project Ember CLI Mirage.',
  slug: 'consumer-driven-weekend',
  releaseDate: 'July 27, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-19-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '1:00:00'
},
{
  number: 18,
  title: 'Reliving All My CS Days',
  description: 'Chase and Jonathan discuss suave code, workshops, metrics, and the ASTs behind Handlebars and HTMLBars',
  slug: 'reliving-all-my-cs-days',
  releaseDate: 'July 20, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-18-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '14:27'
},
{
  number: 17,
  title: 'Ember Training Recap',
  description: 'Chase and Jonathan discuss the what they learned at Ember 2.0 Training in Chicago.',
  slug: 'ember-training-recap',
  releaseDate: 'July 13, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-17-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '23:00'
},
{
  number: 16,
  title: 'Resources and Junk',
  description: 'Chase and Jonathan talk about ten resources that will help you get up and running with Ember.js',
  slug: 'resources-and-junk',
  releaseDate: 'July 6, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-16-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '19:08'
},
{
  number: 15,
  title: 'EmberJax Edits a Podcast',
  description: 'Chase and Jonathan talk about EmberJax, Ember.Evented, and Handlebars printing.',
  slug: 'emberjax-edits-a-podcast',
  releaseDate: 'June 29, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-15-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '16:40'
},
{
  number: 14,
  title: 'Ember IsLand 2.0 Beta',
  description: 'Chase and Jonathan team up with Dan and Robert (from Ember.Land) for a crossover episode in which they discuss all things Wicked Good Ember 2015',
  slug: 'ember-island-two-oh-beta',
  releaseDate: 'June 21, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-14-ember-weekend',
  author: 'Chase McCarthy, Jonathan Jackson, Dan McClain, and Robert Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '22:46'
},
{
  number: 13,
  title: 'The Most Interesting Episode',
  description: 'Chase and Jonathan talk about Ember 1.13 and Ember 2.0.0-beta along with the upcoming talks at Wicked Good Ember.',
  slug: 'the-most-interesting-episode',
  releaseDate: 'June 14, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-13-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '14:53'
},
{
  number: 12,
  title: 'The Curiously Strong Weekend',
  description: 'Chase and Jonathan talk about Ember Simple Auth + Mirage, QUnit helpers, an RFC by Tom Dale, Breadcrumbs and blog posts, component actions, and the growing Ember community.',
  slug: 'the-curiously-strong-weekend',
  releaseDate: 'June 8, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-12-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '19:25'
},
{
  number: 11,
  title: 'E3r W5d with R4t D4a',
  description: 'Chase and Jonathan are joined by Robert Deluca and talk about accessiblity, i18n, jsconf, and a whole lot more!',
  slug: 'e3r-w5d-with-r4t-d4a',
  releaseDate: 'June 1, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-11-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '17:38'
},
{
  number: 10,
  title: 'Meh, Ship it',
  description: 'Chase and Jonathan talk about the growing ember-weekend community, there adventures in fastboot, and a new RFC by Yehuda Katz.',
  slug: 'meh-ship-it',
  releaseDate: 'May 26, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-10-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'http://i.imgur.com/VQmTj1h.png',
  duration: '13:15'
},
{
  number: 9,
  title: 'Interview with the Emberokai',
  description: 'Chase and Jonathan are joined by Paul Elliott, a lead developer at Heroku working on the Dashboard.',
  slug: 'interview-with-the-emberokai',
  releaseDate: 'May 18, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-9-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/XV0c9Xl.png',
  duration: '18:58'
},
{
  number: 8,
  title: 'The Most Private of All APIs',
  description: 'Chase and Jonathan celebrate Glimmer and discuss exploring FastBoot, stubbing services, and the SV Ember meetup.',
  slug: 'the-most-private-of-all-apis',
  releaseDate: 'May 11, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-8-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/XV0c9Xl.png',
  duration: '13:47'
},
{
  number: 7,
  title: 'Champions needed',
  description: 'Chase and Jonathan discuss routable components, ember-cli-mirage (again), JSON API, and the new EmberJax twitter account.',
  slug: 'champions-needed',
  releaseDate: 'May 4, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-7-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/XV0c9Xl.png',
  duration: '17:23'
},
{
  number: 6,
  title: 'Ember in Atlanta',
  description: 'Chase and Jonathan recap their RailsConf experience and talk about Ember meetups',
  slug: 'ember-in-atlanta',
  releaseDate: 'April 27, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-6-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/XV0c9Xl.png',
  duration: '14:26'
},
{
  number: 5,
  title: 'Wicked Good Design',
  description: 'Chase and Jonathan discuss the site redesign, Wicked Good Ember, Ember in Viewport, security patches, the run loop, and Ember Islands.',
  slug: 'wicked-good-design',
  releaseDate: 'April 20, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-5-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/XV0c9Xl.png',
  duration: '13:40'
},
{
  number: 4,
  title: 'IE: Seeya L8er',
  description: "Chase and Jonathan talk Polymer, Ember 2.0 training, Netflix's freedom of responsiblity, and spend some extra time talking about IE8 support.",
  slug: 'ie-seeya-l8er',
  releaseDate: 'April 13, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-4-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/XV0c9Xl.png',
  duration: '13:46'
},
{
  number: 3,
  title: 'Broccoli, but not the vegetable',
  description: 'Chase and Jonathan talk turbolinks, broccoli, and ember-watson.  Spending a little more time than usual discussing the new broccoli tree api.',
  slug: 'broccoli-but-not-the-vegetable',
  releaseDate: 'April 6, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-3-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/XV0c9Xl.png',
  duration: '14:06'
},
{
  number: 2,
  title: 'The Weekend Strikes Back',
  description: "Chase and Jon discuss Ember's new versioned guides, testing in Ember CLI, and an Ember dependency guide for Rubyists.",
  slug: 'the-weekend-strikes-back',
  releaseDate: 'March 30, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-2-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/XV0c9Xl.png',
  duration: '12:35'
},
{
  number: 1,
  title: 'Our First Foray',
  description: "Chase and Jon kick off Ember Weekend discussing EmberSherpa's workshop, EmberObserver, and some resources for beginners.",
  slug: 'our-first-foray',
  releaseDate: 'March 24, 2015',
  lat: 30.291809,
  long: -81.390607,
  filename: 'ep-1-ember-weekend',
  author: 'Chase McCarthy & Jonathan Jackson',
  image: 'https://i.imgur.com/XV0c9Xl.png',
  duration: '10:16'
}
];

