export default [
  {
    number: 11,
    title: "E3r W5d with R4t D4a",
    description: "Chase and Jonathan are joined by Robert Deluca and talk about accessiblity, i18n, jsconf, and a whole lot more!",
    slug: "e3r-w5d-with-r4t-d4a",
    releaseDate: "June 1, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-11-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "http://i.imgur.com/VQmTj1h.png",
    duration: "17:38"
  },
  {
    number: 10,
    title: "Meh, Ship it",
    description: "Chase and Jonathan get talk about the growing ember-weekend community, there adventures in fastboot, and a new RFC by Yehuda Katz.",
    slug: "meh-ship-it",
    releaseDate: "May 26, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-10-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "http://i.imgur.com/VQmTj1h.png",
    duration: "13:15"
  },
  {
    number: 9,
    title: "Interview with the Emberokai",
    description: "Chase and Jonathan are joined by Paul Elliott, a lead developer at Heroku working on the Dashboard.",
    slug: "interview-with-the-emberokai",
    releaseDate: "May 18, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-9-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "https://i.imgur.com/XV0c9Xl.png",
    duration: "18:58"
  },
  {
    number: 8,
    title: "The Most Private of All APIs",
    description: "Chase and Jonathan celebrate Glimmer and discuss exploring FastBoot, stubbing services, and the SV Ember meetup.",
    slug: "the-most-private-of-all-apis",
    releaseDate: "May 11, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-8-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "https://i.imgur.com/XV0c9Xl.png",
    duration: "13:47"
  },
  {
    number: 7,
    title: "Champions needed",
    description: "Chase and Jonathan discuss routable components, ember-cli-mirage (again), JSON API, and the new EmberJax twitter account.",
    slug: "champions-needed",
    releaseDate: "May 4, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-7-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "https://i.imgur.com/XV0c9Xl.png",
    duration: "17:23"
  },
  {
    number: 6,
    title: "Ember in Atlanta",
    description: "Chase and Jonathan recap their RailsConf experience and talk about Ember meetups",
    slug: "ember-in-atlanta",
    releaseDate: "April 27, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-6-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "https://i.imgur.com/XV0c9Xl.png",
    duration: "14:26"
  },
  {
    number: 5,
    title: "Wicked Good Design",
    description: "Chase and Jonathan discuss the site redesign, Wicked Good Ember, Ember in Viewport, security patches, the run loop, and Ember Islands.",
    slug: "wicked-good-design",
    releaseDate: "April 20, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-5-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "https://i.imgur.com/XV0c9Xl.png",
    duration: "13:40"
  },
  {
    number: 4,
    title: "IE: Seeya L8er",
    description: "Chase and Jonathan talk Polymer, Ember 2.0 training, Netflix's freedom of responsiblity, and spend some extra time talking about IE8 support.",
    slug: "ie-seeya-l8er",
    releaseDate: "April 13, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-4-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "https://i.imgur.com/XV0c9Xl.png",
    duration: "13:46"
  },
  {
    number: 3,
    title: "Broccoli, but not the vegetable",
    description: "Chase and Jonathan talk turbolinks, broccoli, and ember-watson.  Spending a little more time than usual discussing the new broccoli tree api.",
    slug: "broccoli-but-not-the-vegetable",
    releaseDate: "April 6, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-3-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "https://i.imgur.com/XV0c9Xl.png",
    duration: "14:06"
  },
  {
    number: 2,
    title: "The Weekend Strikes Back",
    description: "Chase and Jon discuss Ember's new versioned guides, testing in Ember CLI, and an Ember dependency guide for Rubyists.",
    slug: "the-weekend-strikes-back",
    releaseDate: "March 30, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-2-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "https://i.imgur.com/XV0c9Xl.png",
    duration: "12:35"
  },
  {
    number: 1,
    title: "Our First Foray",
    description: "Chase and Jon kick off Ember Weekend discussing EmberSherpa's workshop, EmberObserver, and some resources for beginners.",
    slug: "our-first-foray",
    releaseDate: "March 24, 2015",
    lat: 30.291809,
    long: -81.390607,
    filename: "ep-1-ember-weekend",
    author: "Chase McCarthy & Jonathan Jackson",
    image: "https://i.imgur.com/XV0c9Xl.png",
    duration: "10:16"
  }
];

